repositoryID: The ID of the Artifact Hub repository where the packages will be published to (optional, but it enables verified publisher)
owners: # (optional, used to claim repository ownership)
  - name: featureform
    email: hello@featureform.com
ignore: # (optional, packages that should not be indexed by Artifact Hub)
  - name: etcd